defaults: &execution_defaults
  default_config: live
  default_browser: firefox
live:
  <<: *execution_defaults
  #capybara settings
  default_wait_time: 5
  #urls
  wildfire_site_root: https://account.wildfireapp.com
  wildfire_messenger_root: https://messenger.wildfireapp.com/
  wildfire_analytics_root: https://dashboard.wildfireapp.com/
  wildfire_page_manager_root: https://apps.wildfireapp.com/pages/states/published
  wildfire_promotions_root: https://promos.wildfireapp.com
  wildfire_templates_root: http://templates.wildfireapp.com
  messenger_admin_root: https://messenger.wildfireapp.com/admin
  crystal_ball_root: https://promos.wildfireapp.com/crystal_ball/
  #credentials
  default_user_facebook_address: paloaltofoodie@gmail.com
  default_user_facebook_password: th1sismypassword
  default_facebook_poster_username: burgerwithcheez@gmail.com
  default_facebook_poster_password: th1sismypassword
  facebook_page_url: http://www.facebook.com/PaloAltoFoodies
  facebook_property_name: Palo Alto Foodies
  create_template_property_name: Paloaltofoodies
  default_user_facebook_secret_key: 5ce074c05d67cfd269cd07ce15a869e8
  requires_basic_auth: false
  #others
  default_filter_keyword: cheezburger

staging:
  <<: *execution_defaults
  #capybara settings
  default_wait_time: 15
  #urls
  wildfire_site_root: https://account.wildfirestaging.com
  wildfire_messenger_root: https://messenger.wildfirestaging.com
  wildfire_analytics_root: https://dashboard.wildfirestaging.com
  wildfire_page_manager_root: https://apps.wildfirestaging.com/pages/states/published
  messenger_admin_root: https://account.wildfirestaging.com/admin
  wildfire_promotions_root: https://promos.wildfirestaging.com
  crystal_ball_root: https://promos.wildfirestaging.com/crystal_ball/
  #credentials
  default_user_facebook_address: mountainviewfoodie@gmail.com
  default_user_facebook_password: th1sismypassword
  default_user_facebook_secret_key: 
  #authentication
  authentication_login: wildfire
  authentication_password: A1wNXX4YufOpPI
  requires_basic_auth: true
  
am-test:
  <<: *execution_defaults
  #capybara settings
  default_wait_time: 15
  #urls
  wildfire_site_root: https://account.am-test.wfhack.com
  wildfire_messenger_root: https://messenger.am-test.wfhack.com/
  wildfire_analytics_root: https://dashboard.am-test.wfhack.com/
  wildfire_page_manager_root: https://apps.am-test.wfhack.com/pages/states/published
  messenger_admin_root: https://messenger.am-test.wfhack.com/admin
  wildfire_promotions_root: https://promos.am-test.wfhack.com
  crystal_ball_root: https://promos.am-test.wfhack.com/crystal_ball/
  #credentials
  default_user_facebook_address: paloaltofoodie@gmail.com
  default_user_facebook_password: th1sismypassword
  default_user_facebook_secret_key: 5ce074c05d67cfd269cd07ce15a869e8
  #authentication
  authentication_login: wildfire
  authentication_password: A1wNXX4YufOpPI
  requires_basic_auth: true
