defaults: &execution_defaults
  default_config: live
  default_browser: firefox
live:
  <<: *execution_defaults
  #capybara settings
  default_wait_time: 5
  #urls
  wildfire_site_root: https://account.wildfireapp.com
  wildfire_messenger_root: https://messenger.wildfireapp.com
  wildfire_analytics_root: https://dashboard.wildfireapp.com
  wildfire_page_manager_root: https://apps.wildfireapp.com/pages/states/published
  wildfire_promotions_root: https://promos.wildfireapp.com
  wildfire_templates_root: http://templates.wildfireapp.com
  wildfire_monitor_root: https://monitor.wildfireapp.com
  messenger_admin_root: https://messenger.wildfireapp.com/admin
  crystal_ball_root: https://promos.wildfireapp.com/crystal_ball
  facebook_page_url: http://www.facebook.com/PaloAltoFoodies
  twitter_page_url: https://twitter.com/#!/paloaltofoodie
  #credentials
  default_user_facebook_address: paloaltofoodie@gmail.com
  default_user_facebook_password: th1sismypassword
  default_facebook_poster_username: burgerwithcheez@gmail.com
  default_facebook_poster_password: th1sismypassword
  default_twitter_poster_username: burgerwithcheez
  default_twitter_poster_password: th1sismypassword
  facebook_property_name: Palo Alto Foodies
  create_template_property_name: MyGallery
  default_user_facebook_secret_key: 5ce074c05d67cfd269cd07ce15a869e8
  requires_basic_auth: false
  #others
  default_flag_filter_keyword: cheezburger
  default_delete_filter_keyword: kebab

staging:
  <<: *execution_defaults
  #capybara settings
  default_wait_time: 15
  #urls
  wildfire_site_root: https://account.wildfirestaging.com
  wildfire_messenger_root: https://messenger.wildfirestaging.com
  wildfire_analytics_root: https://dashboard.wildfirestaging.com
  wildfire_page_manager_root: https://apps.wildfirestaging.com/pages/states/published
  wildfire_promotions_root: https://promos.wildfirestaging.com
  wildfire_monitor_root: https://monitor.wildfirestaging.com
  wildfire_templates_root: http://templates.wildfirestaging.com
  wildfire_front_page: http://www.wildfirestaging.com
  messenger_admin_root: https://messenger.wildfirestaging.com/admin
  crystal_ball_root: https://promos.wildfirestaging.com/crystal_ball
  facebook_page_url: http://www.facebook.com/PaloAltoFoodies
  twitter_page_url: https://twitter.com/#!/paloaltofoodie
  #credentials
  default_user_facebook_address: paloaltofoodie@gmail.com
  default_user_facebook_password: th1sismypassword
  default_facebook_poster_username: burgerwithcheez@gmail.com
  default_facebook_poster_password: th1sismypassword
  facebook_property_name: Palo Alto Foodies
  create_template_property_name: MyGallery
  default_user_facebook_secret_key: 5ce074c05d67cfd269cd07ce15a869e8
  requires_basic_auth: true
  #others
  default_flag_filter_keyword: hamburger
  default_delete_filter_keyword: pizza
  #authentication
  authentication_login: wildfire
  authentication_password: A1wNXX4YufOpPI
  requires_basic_auth: true
  
am-test:
  <<: *execution_defaults
  #capybara settings
  default_wait_time: 15
  #urls
  wildfire_site_root: https://account.am-test.wfhack.com
  wildfire_messenger_root: https://messenger.am-test.wfhack.com
  wildfire_analytics_root: https://dashboard.am-test.wfhack.com
  wildfire_page_manager_root: https://apps.am-test.wfhack.com/pages/states/published
  wildfire_promotions_root: https://promos.am-test.wfhack.com
  wildfire_monitor_root: https://monitor.am-test.wfhack.com
  wildfire_templates_root: http://templates.am-test.wfhack.com
  wildfire_front_page: http://www.am-test.wfhack.com
  messenger_admin_root: https://messenger.am-test.wfhack.com/admin
  crystal_ball_root: https://promos.am-test.wfhack.com/crystal_ball
  facebook_page_url: http://www.facebook.com/PaloAltoFoodies
  twitter_page_url: https://twitter.com/#!/paloaltofoodie
  #credentials
  default_user_facebook_address: paloaltofoodie@gmail.com
  default_user_facebook_password: th1sismypassword
  default_facebook_poster_username: burgerwithcheez@gmail.com
  default_facebook_poster_password: th1sismypassword
  facebook_property_name: Palo Alto Foodies
  create_template_property_name: MyGallery
  default_user_facebook_secret_key: 5ce074c05d67cfd269cd07ce15a869e8
  requires_basic_auth: true
  #others
  default_flag_filter_keyword: chickenburger
  default_delete_filter_keyword: chimichanga
  #authentication
  authentication_login: wildfire
  authentication_password: A1wNXX4YufOpPI
  requires_basic_auth: true
