defaults: &default_users
  the default user:
    email: paloaltofoodie@gmail.com
    password: th1sismypassword
  a user with a delinquent account:
    email: alistair.hutchison+delinquent@wildfireapp.com
    password: w1ldf1r3
  a user with access to all applications:
    email: alistair.hutchison+allapps@wildfireapp.com
    password: w1ldf1r3

staging:
  <<: *default_users
  a user with existing properties:
    email: alistair.hutchison+staging@wildfireapp.com
    password: password1
  the template user:
    email: paloaltofoodie@gmail.com
    password: th1sismypassword
  a user with two accounts:
    email: alistair.hutchison+twoaccounts@wildfireapp.com
    password: w1ldf1r3
    
am-test:
  <<: *default_users
  the template user:
    email: paloaltofoodie@gmail.com
    password: th1sismypassword
  a user with no permissions:
    email: alistair.hutchison+no_permissions@wildfireapp.com
    password: password1
  a user with all permissions:
    email: alistair.hutchison+all_permissions@wildfireapp.com
    password: password1
  a company admin:
    email: alistair.hutchison+company_admin@wildfireapp.com
    password: password1
  an account admin:
    email: alistair.hutchison+account_admin@wildfireapp.com
    password: password1
      
live:
  <<: *default_users
  the template user:
    email: paloaltofoodietemplateuser@gmail.com
    password: th1sismypassword
  a user with two companies:
    email: alistair.hutchison+twocompanies@wildfireapp.com
    password: password1
  a user with two accounts:
    email: alistair.hutchison+twoaccounts@wildfireapp.com
    password: password1