#!/usr/bin/env bash

if which wfvm > /dev/null; then
	source `which wfvm` 1.9.3-p0
fi

if [[ "1.8" = $(ruby -e 'puts RUBY_VERSION[0,3]') ]]; then
	echo "Please use ruby > 1.8 to develop this application"
	exit 1
fi

set -ex

bundle
