#!/usr/bin/env bash

if which wfvm > /dev/null; then
	source `which wfvm` 1.9.3-p0
fi

set -ex

. script/bootstrap

bundle exec rake CONFIG=staging BROWSER=firefox SAUCE_OS=LINUX cuke:stagingcomplete
