#!/usr/bin/env bash

if which wfvm > /dev/null; then
	source `which wfvm` 1.9.3-p0
fi

set -ex

. script/bootstrap

if [ -z "$RAKE_TASK_NAME" ]; then
  echo "You must set the RAKE_TASK_NAME variable"
  echo "Usage: RAKE_TASK_NAME=\"<task_name>\" script/cibuild"
  exit 1
fi

bundle exec rake cuke:$RAKE_TASK_NAME
